spring:
  data:
    mongodb:
      uri: mongodb+srv://prajwalnarute:Prajwal%40123@foodapp.jdid3cd.mongodb.net/expense_tracker?retryWrites=true&w=majority&appName=foodapp
  application:
    name: ExpenseTrackerAPI

server:
  port: 8080

expense:
  opening-balance: 50000
